openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /firstEndpoint:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      parameters:
        - name: firstDateOnRoot
          in: query
          schema:
            type: string
            format: date
        - name: secondDateOnRoot
          in: query
          schema:
            type: string
            format: date
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: integer
  /secondEndpoint:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      parameters:
        - name: firstDateOnRoot
          in: query
          schema:
            $ref: '#/components/schemas/SomeObjectType'
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: integer
components:
  schemas:
    SomeObjectType:
      properties:
        firstNestedDate:
          type: string
          format: date
        secondNestedDate:
          type: string
          format: date
